server:
  port: 8080
  servlet:
    context-path: /springweb

spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
  redis:
    host: 127.0.0.1
    port: 6379
    password: # 默认为空
    jedis:
      pool:
        max-active: 20  # 连接池最大连接数，使用负值则无限制
        max-wait: -1 # 连接池最大阻塞时间，使用负值表示没有限制
        max-idle: 10 # 连接池最大空闲连接
        min-idle: 0 # 连接池最小空闲连接
    timeout: 1000 # 连接超时时间

mybatis:
    mapper-locations: mapper/*.xml


