server:
  port: 8080
  servlet:
    context-path: /springweb

spring:
  # 数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    druid:
      # 初始化大小
      initial-size: 8
      min-idle: 5
      # 最大连接数
      max-active: 20
      # 连接最大等待时间
      max-wait: 1000
      # 间隔多久检测一次需要关闭的空闲连接 毫秒
      time-between-eviction-runsMillis: 60000
      # 连接在连接池中最小生存的时间，毫秒
      min-evictable-idle-timeMillis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      # 监控统计拦截的过滤器 不加监控界面sql无法统计 wall用于防火墙
      filters: stat,wall,log4j,config
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      use-global-data-source-stat: true
      # 过滤器
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        url-pattern: /*
      stat-view-servlet:
        # 白名单IP
        allow: 127.0.0.1
        # 黑名单IP
        deny:
        # 登录账号和密码
        login-username: root
        login-password: root
        # 启用重置数据功能
        reset-enable: true
        enabled: true

  redis:
    host: 127.0.0.1
    port: 6379
    password:                         # redis密码，默认为空
    jedis:
      pool:
        max-active: 20                # 连接池最大连接数，使用负值则无限制
        max-wait: -1                  # 连接池最大阻塞时间，使用负值表示没有限制
        max-idle: 10                  # 连接池最大空闲连接
        min-idle: 0                   # 连接池最小空闲连接
    timeout: 1000                     # 连接超时时间

mybatis-plus:
  mapper-locations: mapper/*.xml


